- MeltShiny.R
The image above displays the program's ability to both parse and modify an unprocessed input csv into something that can be utilized by MeltR. There is a ribbon at the top that contains a drop down menu. In the file menu, thus far, we have the upload button implemented. The user needs to input the pathlengths, separated by comma, as they upload their input files. As it stands, there is also code(not fully implemented) that allows the user to upload multiple csv files that can be appended. The idea is that this would all work through the same upload interface seen in the image.
> Adding the working R code for MeltShiny2.0

- MeltShiny.R
**What was implemented?** 
-A "Data Visualization" tab was created at the top of the navigation bar.
-Plots the display each absorbance reading from user inputted data.
-A slider that controls two vertical lines to mark the beginning & end of the points 
**How to access this tab** 
-This tab remains empty until the user inputs a valid CSV file. 
-Once the user inputs a valid file, the contents within the "Data Visualization" tab will appear.
**Why is this Important?**
-Allows the user to visualize their imported data.
-Provides the necessary tools for the next contributor to start implementing other functionalities on the data. 
**Demonstration**
-Here is a video demonstrating the implemented feature. 
https://user-images.githubusercontent.com/114530395/196327151-6a63eec4-3842-4c87-b023-5a …
> Data Visualization Feature

- MeltShiny.R
**Changes Made**
-Added Drop-Down menu named "Plots"
-Dynamic number of panels are added under the drop-down based on the number of absorbance readings added
**Why Is this Important**
-These panels will contain the contents that were previously in the "Data Visualization" tab
-Reiteration: Each individual absorbance reading will be given its own tab for visualization purposes. 
**Video Demonstration**
Here is a video demonstrating the contents above. 
https://user-images.githubusercontent.com/114530395/196616887-dcf9cb74-ba46-4821-8cdb-9854311f27c0.mov
> Dynamic Drop-Down for Absorbance Data

- MeltShiny.R
I've implemented the ability for the user to append multiple datasets into our program. This is necessary, as researchers will be working with samples from multiple runs of an experiment. They need to ability to compare those samples, and that requires the ability to input multiple datasets. It should be noted that under this implementation, researchers can upload however many datasets they wish. Whether uploading the initial dataset or subsequent ones, all datasets need to be uploaded through the single upload button found by clicking file in the ribbon, followed by the add data button.
The code first cleans the additional datasets, identically to how the first was cleaned. It then appends the cleaned dataset to the bottom of the existing one. The sample number is incremented …
> Append datasets

- MeltShiny.R
**Issue That This Request Addresses**
Currently in our main branch some of the dropdown panels repeat themselves when importing more than one dataset. This branch was created to solve and address this issue, so that when multiple datasets are uploaded we see the correct number of uploaded samples.
**Small Change**
-Did some light code cleaning(added whitespace when assigning variables)
**Demonstration of Changes**
-Current Implementation
https://user-images.githubusercontent.com/114530395/198160253-693ba50e-742a-40d0-8403-2f19892f3596.mov
-New Implementation
https://user-images.githubusercontent.com/114530395/198160440-fcbf7548-dcef-429a-be36-baef084403a7.mov
> Fixed Overwriting Issue

- server.r
- ui.R
**Changes Made**
-Changed "Plots" tab to "Analysis"
-Changed the layout to display each sample page in an tabsetPanel layout, instead of a drop down.
**Video Demonstration**
-Here is a video demonstration of my changes.
https://user-images.githubusercontent.com/114530395/200490579-806787d0-f7b8-44e8-849f-0ee99faf175b.mov
> Changed Layout of "Analysis" Tab

- global.r
- server.r
- ui.R
Overview
I added a new tab that will contain all of the result pages. The only result page added so far is one that shows the graphed Van't Hoff Plot. It takes the natural log of the concentration and the inverse of the temperature and graphs it. This uses Melt R's fitting results in order to create the graph. Below is pictured what the new panel and graph look like.
> Van't hoff plots

- server.r
- ui.R
This update features the removal of the sequence info widget after the first dataset is uploaded. 
Below are images to showcase these changes.
This image shows how the widget will look when the user first uploads a file. 
This image shows how the widget is removed after the file is uploaded.
> Sequence info

- global.r
- server.r
**For each respective sample:**
-Ability to view the individual fitted line on top of the raw data on the same plot. 
-Ability to view the individual fitted line, first derivative sketch, and raw data on the same plot. 
**Raw Data (Nothing Selected)**
**Raw Data + First Derivative (First Derivative Selected)**
**Raw Data + Best Fit (Best Fit Selected)**
**Raw Data + First Derivative + Best Fit (Best Fit & First Derivative Selected)**
> Best Fit/Fitted Line Attribute 

- global.r
**Objective** 
Our client requested the ability to distinctly see the maximum value of the first derivative plot when viewing. This pull request serves as a fulfillment to this request by highlighting the maximum value in red.
**Minor Change**
Relocated data creation code from `constructFirstDerivative()` to `constructObject()` to make the plot function more straight-forward.
**Photos Demonstrating the Addition**
> Highlighted max value

- README.md
This update includes the addition of headers, such that readers can easily find the most relevant sections of the README documentation.
> Added headings to the README file

- code/ui.R
Implementing "Fit" tab in ribbon.
> Implemented Fit Tab

- code/app.R
- code/global.r
- code/install.R
- code/server.r
- code/ui.R
This update includes the formatting and cleaning of all program files to follow a clear coding standard.
Additionally, there are small bug fixes such as the download buttons for the Van't Hoff plot and the results table.
Some small UI tweaks include the removal of the Analysis tab and the inclusion of a Analysis menu, under which are the Graphs and Fit tabs. 
Lastly, there are minor features, including a checkbox which allows for users to show the graph for blanks during the analysis step.
> Cleaning and Formatting code

- code/ui.R
This pull request adds a help page to the application. It discusses what each page of the app does and what should happen when you hit the functions. It goes in detail about how to upload data, save results, and use the graphs. Attached to this pull request is a picture.
> Adding info to help page

- code/server.r
This code adds pop up screens when a users input, or lack of input, would have previously crashed the code. Pictured is the screen that comes up when you leave an input box blank. The code also checks that the blank is a single integer number, removes spaces from the helix info and pathlength boxes, and checks that if you select DNA as your helix type you only use a wavelength of 260. The pop ups will appear show a message upon the user uploading a file. They then allow the user to fix their inputs at which point they will read their file so the application can run.
> Input checking -> Issues 67 and 66

- code/server.r
This code fixes the error where the graphs weren't showing up because of the input checking. The graphs now show up if the inputs are correct.
> Fixing Graph Error

- README.md
Updated the readme so that the instructions to download the program, install its dependencies, and running the program are more clear. 
I also removed the demo data inputs, as the program can now handle other inputs.
> Updated the Readme for clarity and instructions

- code/server.r
- code/ui.R
Before the VantHoff loads, it displays a "Loading..."
> Adding loading text to Vant Hoff

- code/server.r
Split up HelixID and the sequences into 2 different boxes
> split changes

- code/server.r
- code/ui.R
Nucleic spelling which is wrong where you enter the sequence on the website is fixed
> Nucleic is spelled incorrectly where you enter the sequence on the website #133

- code/server.r
- code/ui.R
A dropdown was introduced to Nucleic acid type .
Give an option to choose between Sequence and coefficient.
> Split the nucleic acid type into 2 different inputs #118

- code/server.r
- code/ui.R
Fixes #147 
The issue has two parts: layout and a new help menu, this draft has all of the layout changes done
The client asked for these changes because it makes more sense for a user to have it this way
I just had to switch around a few UI components in the ui file and add some bordering and change a title of an input
*screenshots not applicable*
> Layout Changes for the sprint

- code/ui.R
Fixes #159 
Simple cosmetic change for input field directed by client within ui.R.
> Changed input text

- code/deploy.R
- code/global.r
- code/install.R
- code/server.r
- code/ui.R
Fixes #168 
Descriptive comments need to be added to the top of important components within application. This is simply to contextualize the component in the holistic view of the application. Later iterations will involve removing unnecessary comments throughout the program.
> Descriptive Commenting

- code/deploy.R
- code/global.r
- code/install.R
- code/server.r
- code/ui.R
Issue #169 had syntax error for commenting. This was breaking the entire infrastructure, and therefore the automated deployment
> Fixing Zohaib's errors

- code/server.r
Fixes [181](https://github.com/oss-slu/MeltShiny/issues/181)
This pull request is a re-upload of another pull request that was previously merged, then reverted. Information regarding the changes can be found within [this](https://github.com/oss-slu/MeltShiny/pull/183) pull request. Test cases were provided from [this](https://github.com/oss-slu/MeltShiny/issues/181#issuecomment-2336201373) thread comment.
> (Re-Upload) Resolve Bug Causing Internal Errors with New Data Format (AYGU-1_MeltR)

- code/server.r
- code/ui.R
Fixes #175 
A button was added on the Help page to allow the user to easily return to the home page.
To allow the user to return to the home page more easily.
A sidebarPanel and button were added to the Help page in the ui.R file. An event handler was also added to server.R to give functionality to the "Back to Home" button.
MeltShiny was launched and the button was tested to ensure it brought the user back to the home page.
Since the button appeared successfully, this ensured that the changes in ui.R were successful. And since the button was functional, this showed that the changes made in server.R were also successful.
*screenshots*
> Added "Back to Home" button on Help page

- code/server.r
- code/ui.R
Fixes #189
I changed text "Sample number of blank" to "Cell number of blank" as well as Select the wavelengthID" to "Enter the wavelength" and converted it to a textbox and removed all "datasets uploaded" checkboxes.
*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*
I changed text from the ui file for renaming cell number of blank and wavlength id then deleted the datasets uploaded checkbox as well. In the ui file i also changed the code for wavelength id to support entering the users own number as opposed to it being a selection. In the server file I made datasetsUploadedID a reactive variable that upon the clicking of the upload data changes …
> fixes_Issue_189

- code/server.r
- code/ui.R
Fixes #205 
Spelling from Van't Hoff to van't Hoff
*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*
I changed the spellings found throughout the ui.R and server.r files. 
I only changed van't Hoff spellings that are visible to the user.
It was a spelling error, and the client asked for us to fix it. 
I ran it locally, and it was solved. 
**Screenshots that show the changes (if applicable):**
> Misspelling of van't Hoff

- .github/workflows/deploy-shiny.yaml
- code/server.r
- code/ui.R
Fixes #195
I added a reset button to the main page that shows up after an initial upload of data to reset all inputs
This allows users to reset all inputs and plug in new data/datasets
I added to ui.r to create the reset button and created the logic behind it in server.r. Mainly added "update____" to reset all other inputs to their default values and "enable" functions to reenable all inputs
After saving code, I ran the meltShiny command to see if the reset button showed up and if it reset all values when clicked.
**Screenshots that show the changes (if applicable):**
After Uploading Data: 
After clicking Reset Button:
> Enable Reset Option for Dataset Upload #195

- code/server.r
Fixes #issue_222
I changed the file creation when downloading data.
*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*
I changed the area of the server that was responsible for naming the downloaded file.
Previously if no user input was given there was no default name in place so the data file would be unusable after download.
*Here, describe the issue that you are fixing with this code, and why your code fixes it.*
The issue is the code only handles user input and in the case that the user types nothing the server does not know how to properly respond. My code gives default names should the user not type one in and that …
> Adding default file name when exporting data

- code/server.r
Fixes #issue_231
Error handling was added for incorrectly formatted .csv files that caused the program to crash or display data incorrectly.
I changed the server functionality of the program to detect and handle .csv formatting issues such as there not being exactly 4 columns. Additionality the columns now must follow a pre defined naming structure: Sample, Pathlength, Temperature, Absorbance. The program also detects if there are empty data cells and alerts the user that they need to be addressed before processing. The program also does not allow the user to upload a file that is not a .csv.
These features were added to resolve the issue of the program crashing with incorrectly formatted files when they are submitted and to establish clarity as to what the issue was with the file. 
The …
> #issue 231

- code/server.r
- code/ui.R
Fixes #issue_number
had to resolve some case sensitivity issues in the file paths provided in the code. 
*I observed that during the deployment, the files and their paths in the code are expected to be case sensitive . But the paths in the code for some files have some opposite cases*
*I checked the logs and build warning during the build initially overlooked some, so had to make multiple commits. *
*The application is now active on the deployment environment and working as it was before when I deployed it from this new branch*
**Screenshots that show the changes (if applicable):**
earlier:
now:
> Akurapati env

- code/server.r
- code/uiParts/file.r
Fixes #issue_258
the functionality of file.r was changed so it could be hidden.
I changed the way file.r was displayed after uploading data. 
This was changed to make the data more prevalent on the screen.
This was not an issue to fix but a quality of life update. 
I changed the sidebar of file.r to be able to be hidden when the data was uploaded so that the user could see the data better. 
I modified file.r and server.r. I gave the file.r sidebar a variable name so it could be hidden or shown and had the server.r file interact with those variables when data was uploaded. 
I tested this by ensuring previous functionality was retained and the new functionality worked with the test files. 
By ensuring program functionality was retained and the added functionality was correct when the test …
> Issue_258 hiding sidebar for file.r
