oss-slu/MeltShiny

- global.r
- server.r
- ui.R
In this batch of code I added a new tab to show the results tables that MeltR outputs. These mimic tables that were also shown on MeltWin. This allows the user to see the same results tables that they would have been able to view in MeltWin. This tab also shows all the tables in a more coinvent manner than the automatic output that the terminal provides. This closes issue 19. I also updated the code so that the van't hoff plots only rely on the global variables and no longer MeltR directly.
> Results table

- code/install.R
- windowsPackageInstaller.bat
This update includes a R package installer file for windows. The windowsPackageInstaller.bat file can be double clicked like any exe file and will install all the necessary packages for MeltShiny. When the user double clicks the file, a terminal appears on screen and indicates whether any packages need to be downloaded, in which case it will proceed to do that. Once installation is completed, the user will be shown a list of all the necessary packages. A checkmark next to them indicates they were downloaded successfully. In this case, the user can press any key to exit the terminal. If a package was unsucessful in being installed, the terminal will show an x next to that package name. The terminal will also display a command for that package(s) that the user can enter in the RStudio …
> Implemented a windows package installer script

- .gitignore
- code/global.r
- code/server.r
- code/style.R
- code/ui.R
This pull request brings fitting to our application, more specifically automatic fitting. This is done using MeltR's **BLTrimmer** function to test different baselines from an inputted number. If the user opts to utilize automatic fitting, selective results update upon automatically fitting. More specifically the "summary of the three methods" and the "% error between methods".
Closes #74 
- Added `Rplots.pdf` to `.gitignore`. This is an unnecessary auto-generated file. 
- Implemented UI for "Automatic" tabsetPanel.
- Added Method 3 to the "Summary of the Three Methods" within the Results Table
- Selective results update upon automatically fitting. 
- Updated Absorbance readings within the table to accurately display the correct values. 
**Figure 1** highlights the fixed values for the …
> Automatic Fitting Feature

- MacOS_Scripts/MeltShinyUpdate.command
- README.md
- Windows_Scripts/MeltShinyUpdate.bat
Addresses an issue our client reached out to us for regarding recent changes in issue #95
The original implementations regarding the update scripts was accurate but did not address an edge case. This being if users altered the file structure of the MeltWin2.0 application when unzipping its contents. The original implementation deleted all neighboring subdirectories to the update script directory and replaced with updated contents of the application. This could potentially cause loss of important data on user drives, given this specific circumstance.
This change implements a check on the name of the parent directory, to ensure that the program file structure is as is defined by the repository. In addition, only the contents within the code subdirectory will be updated. For updates …
> Issue95fix

- code/server.r
Checks to see if all points are removed from Vant Hoff. If all points are removed, then it resets the plot to the original values.
> Van't Hoff, all points removed bug

- README.md
This issue is related to the Windows scripts not running because Rscript is not recognized as a program. This issue is probably happening because the README might not be clear enough in the section for adding R to the PATH variable, so it needs to be made more clear.
There is also another issue that I ran into involving the dependencies installer which also needs more testing, with the package installer.
I have tested it on my own alternate PCs and ran into these issues. So now I have to test it on Lab computers to see if I can replicate it, then fix it.
> WIP on issue114

- code/server.r
This pull request solves #137 
The issue revolved around that a number of variables being global that should've been local variables. In R, global variables persist across the entire R session. The reason the disconnect did not occur locally was because developers would constantly open and terminate a new R session when the quit the application, hence the global variables were reset each time. However if the application is hosted, a user will have their own R session that will persist over page refreshes. A global data frame variable would then persist and contain datasets of previous program runs, which lead to multiple errors. 
This fix simple creates local variables and configures them within server.R to reset upon new dataset uploads.
> Reset global variables on new dataset

- code/server.r
Fixes #148 
Essentially the datasets uploaded checkbox signaled the processing of the already uploaded data. 
It was redundant and only a deterrant to an initial server disconnect issue before we knew what was the root cause. 
I've programmatically had this auto-checked post data upload. After uploading a dataset, processing is immediately initiated.
> Programmatically check uploadedID after initial preprocess

- code/global.r
- code/server.r
Fixes #153 
A logging function was created globally (global.r) to introduce checkpoints during the application run (logging details at certain points within server.r).
As of currently, MeltShiny is a black box to both users and developers. There is no logging or indication of successful processing which makes developing and debugging a pain. These logged statements will indicate exactly when and where the application may fail which can also be crucial to debugging the R server issues seen within shinyapps logs.
> log points

- .github/.gitignore
- .github/workflows/deploy-shiny.yaml
- code/deploy.R
- deployment/automaticDeployment.md
- dockerfile
Fixes #issue_number 165
automaticDeployment.md was added to the repository. deploymentPlan.md was added to .gitignore, so the original plan can still be seen with those access to the repository. 
It was changed because I will no longer be part of the team, so the next group can hopefully understand what the whole CI/CD process of MeltShiny. 
*Here, describe the issue that you are fixing with this code, and why your code fixes it.*
N/A
N/A
*Here, get into detail about what files you modified, and talk about the most important lines in regards to fixing the issue.*
automaticDeployment.md is the most important file. docker file, deploy-shiny.yaml, and deploy.r are also important for extra details.
> CI/CD Documentation

- code/server.r
Fixes [181](https://github.com/oss-slu/MeltShiny/issues/181)
I revised the parsing logic in `server.r` to comply with MeltR's expected dataset format for files that have the same structure as `AYGU-1_MeltR`.
As stated in the user story, going forward, user input data will be structured like `AYGU-1MeltR.csv`. The current code strictly supports input files structured like `test.csv`. My code now supports input files structured like `AYGU-1_MeltR.csv`, instead of input file structured like `test.csv`. 
The new input file standard, `AYGU-1MeltR.csv`, already complies with MeltR, almost. I have added one line that manipulates the data before it interacts with MeltR: `data <- raw_data %>% arrange(Sample)`. This line sorts …
> Resolve Bug Causing Internal Errors with New Data Format (AYGU-1_MeltR)

- code/ui.R
Fixes #176 
What was changed?
The dropdown menu from the Files tab has been removed, so when you click on 'Files', it will bring you to the page where you input a file into the system.
Why was it changed?
This was changed because the dropdown menu was redundant and the File tab can have the same functionality on its own.
How was it changed?
ui.R was updated so that the Files tab no longer is a dropdown menu, but is now a tabPanel button on its own.
How was it tested
Program was run and the 'Add Dataset' dropdown menu has been removed, with the File button having all of its functionality.
Screenshots that show the changes (if applicable):
> removed dropdown for 'Add Dataset'

- code/ui.R
Fixes #177
I changed the order of the sections
"Specify nucleic acid type"
"Decide if you want to have the molar...".
The order of the two sections was changed to improve the flow of the ui, which would make it more logical for users to first decide on required information before specifying the nucleic acid type. 
I adjusted the code in the sideBarPanel, moving the section for "Decide if you want..." above the "Specify nucleic acid type"
I tested it by running the MeltShiny command to confirm that the "Decide if you want.." section was above the "Specify nucleic acid type" section.
**Screenshots that show the changes (if applicable):**
Before: 
After:
> Move "Decide if you want to have the molar…” to top #177

- code/install.R
When following the development environment setup instructions from README.md, I encountered an error when running the MacOS_Scripts/MeltShinyDependenciesInstaller.command. The error was:
```
#!/usr/bin/env Rscript --vanilla ; exit;
MacOS_Scripts/../code/install.R: line 4: syntax error near unexpected token `('
MacOS_Scripts/../code/install.R: line 4: `requiredPackages <- c("dplyr",'
```
MeltShinyDependenciesInstall.command was calling code/install.R script. This script did not have the shebang for Rscript at the top of the file (there was a comment at the top instead, followed by the shebang for Rscript line: `#!/usr/bin/env Rscript --vanilla`. Moving this line to the top of the script fixed the problem.
After making this change, I ran the …
> Dev environment fix

- code/server.r
- code/ui.R
Fixes #190 
The textInput that prompts the user to input a temperature now autopopulates with the highest temperature found in the dataset.
This change was made to aid the user so they won't have to do as many steps to process the data.
The dataset is opened and the highest temperature in the "Temperature" column is extracted. This temperature is inputted into the inputText field so that the user can see which temperature is being used.
The program was run with test files and the correct max temperature was found and used.
> Automatically Populate "Enter Temperature" Field with Highest Temperature from Data #190

- code/server.r
- code/ui.R
Fixes #208 
A manual option for inputting the maximum temperature was added.
In case there's a discrepancy in the data causing an unusual max temperature, the user can input their own desired max temperature.
A button was added to sense for when the temperature field was changed. If this button is pressed, the data processing and Vant Hoff plots are redone, using the manually inputted temperature.
App was rerun and data was inputted with the highest temperature automatically found. Then, a new highest temperature was manually inputted and it was made sure that the Vant Hoff plot was still being displayed properly.
> added manual option for temperature input

- code/server.r
Fixes #214
I deleted unnecessary columns from IndividualFits *.xlsx output that is downloaded
These columns are not necessary, and presented an obstruction to the file's readability and relevance.
I changed the server.r file, specifically lines 663-685. Implemented condiitional removal by adding "select(-c(Delete, ID))" specifically for individual fits. In addition, when "All of the Above" is selected, my additions ensure that the two columns are still not included in IndividualFits. 
I reran the MeltShiny command two times, inputted all test data, downloaded the excel file with first "Individual Fits" selected and then with "All of the Above" selected to ensure that the two columns were not …
> Remove Unnecessary Delete and ID Columns from IndividualFits *.xlsx Ouput #214

- code/server.r
Fixes #228
A help message was added to the sequence input section.
The previous version only had a placeholder instead of a help message.
A descriptive message of what sequences need to be inputted and the exact formats that they need to be in was added.
MeltShiny was run and the help button was pressed so the message could be viewed.
> Added help message to Sequence Input section

- code/server.r
Fixes #232 
If invalid sequences are inputted, the system no longer freezes. Instead, it displays an error message and allows the user to reenter a sequence. This is performed for both RNA and DNA. 
To prevent application freezing and enhance error handling.
Existing error checks were altered to effectively check if sequence inputs are valid. If they are valid, a validator variable is set to true and the program is allowed to continue.
The program was run and both RNA and DNA inputs were tested with invalid sequences. The error message was displayed and the user was allowed to reenter a sequence. It was also tested with a valid sequence to ensure that the program operated properly under correct …
> Prevent Application Freezing with Invalid Sequence Inputs

- code/server.r
Fixes #239
The Individual Fits table generation code was slightly altered so that it displays and can be downloaded properly. The error was simply that a logging message in the table creation function was creating a block that didn't allow the table to be displayed.
So that the Individual Fits table can be viewed and downloaded.
A log message was blocking shiny's functionality and not allowing it to continue generating a table. It seems that attempting to write the log to the terminal while generating a shiny table at the same time caused some sort of deadlock or data-flow discrepancy, so the log message was removed.
MeltShiny was run, the Individual Fits table was viewed and properly displayed. I …
> Individual Fits Table Properly Displayed

- code/server.r
- code/ui.R
Fixes #240
Made an "Advanced Settings" section on the same inputs page, with inputs that are usually default inputs and are rarely changed. Upon clicking the Advanced Settings button, users are able to still change the values if they choose to do so, otherwise everything will remain with the default inputs. This change makes the inputs page cleaner. 
Since many of the sections have default inputs, the UI is cleaner if these sections are in a separate dropdown. 
I modified the UI file and the server file. I added a button labeled "Advanced Settings" that toggles the visibility of the advanced input fields. I wrapped the advanced input fields inside a div that can be shown/hidden using ShinyJS. Inside server.r, I used …
> Changing the UI to have an Advanced Setting section

- code/global.r
Fixes #issue_251
The crucial detail about the program that was changed was the way that data was being read into the creation of plots for the analysis of the melting curves. 
A function was what specifically was changed and it was changed by modifying the variable of a function that was responsible for specifying what data was assigned to be used later for graphical display. 
This was changed because the data that was being used for the first graph was not correct and it was causing formulas that were ran on it to return NA resulting in a feature such as displaying the first derivative not working. 
*Here, describe the issue that you are fixing with this code, and why your code fixes it.*
The issue that is fixed with the code is that the subset of data that is being compared in the …
> Issue_251 first derivative displaying incorrectly

- code/modules_1.r/meltR_obj_creation.R
- code/modules_2/VantHoffPlot.R
- code/server.r
Fixes #257 
When creating the meltR object, the correct parameters are passed to be able to create the Vant Hoff plot. 
With homoduplex and heteroduplex files, the Vant hoff plot wasn't being properly created, causing the application to crash. 
Added new parameters to the process_meltR_object() function, allowing it to properly create the Vant Hoff plot. 
Tested with each of homoduplex, heteroduplex, and monomolecular files to ensure the program ran without error and that Vant Hoff plots were created for both homoduplex and heteroduplex files (but not for monomolecular).
> App works for Heteroduplex and Homoduplex files

- code/global.r
- code/modules_2/DynamicTabs.R
- code/server.r
Fixes #268 
The manual baseline trimming functionality under the Fit tab of the Analysis section was completed and made functional. 
constructAllPlots() was modified to apply baseline trimming.
Reactive values were added to trigger the graphs to refresh with the new baseline trimming.
Before these changes, the fit button existed but didn't have any functionality. Now, the graphs can be cut off according to the manually set baseline ranges.
constructAllPlots() was modified so that data and data2 are filtered when the fit button is clicked. The graphs will regenerate and use these new filtered datasets.
plotRefreshTrigger was added in server.R so that the plots are refreshed after the fit button is clicked.
**How was it …
> Manual Baseline Trimming (Fit) is Functional
